### ISSUE TITLE
Feature Request: Create matching files if none exist.

### ISSUE THREAD

**Issue by phyllisstein** [nick125/related#3]
Hi there! Just caught this on the Atom site and immediately switched over from my previous, Rails-specific solution---nice work! I was just wondering, though, if it'd be possible to have the package give one the option to create matching files when no matches are returned. I glanced at the code to see if I could submit a helpful PR, but the Atom API is still a dark continent to me.

Thanks in advance for considering it, and for your lovely work on this!

**Comment by nick125** [comment]
Hey! I'm glad the package was useful and I appreciate the kind words. 

I'm kind of hesitant to make it a global option, as some patterns might expand to paths that don't really make a lot of sense. What are your thoughts on making this a per-result configurable option? Something like

``` cson
"(.+)/(.+)\\.coffee": [
    "create#$1/$2\\.html"
]
```

**Comment by phyllisstein** [comment]
That totally makes sense. And adding that flag would definitely cover my use-cases, so I'm down! Thanks so much for your speedy reply!

**Comment by nick125** [comment]
Added this functionality in  d165618, supporting the "#create" suffix on results. This should be available as v0.3.0.
